version: 0.1

phases:
  install:
    commands:
      - echo Installing ...
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
      - export NVM_DIR="/Users/mat/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
      - nvm install 6.9
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - aws s3 cp $ENV_FILE .env
      - npm run package
artifacts:
  files:
    - target/slackbot.tar.gz
  discard-paths: yes